# Change these first
owner: Foca-Software # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Autogestión Clientes
    url: https://sacautogestion.focasoftware.com/index
  - name: Receptor
    url: https://receptordebocloud.debo-cloud.com/api-recepcion/test
  - name: Backend Mercado Pago Foca
    url: http://mp.focasoftware.com/webservices/testFront
  - name: Backend Mercado Pago v2 Foca
    url: https://mercadopagocloud.focasoftware.com/mercadopago/message-alive
  - name: Backend Puma Foca
    url: https://pumacloud.focasoftware.com/puma/message-alive
  - name: Backend Central Info Foca
    url: https://centralinfo.focasoftware.com/message-alive

assignees:
  - ArielGQ

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.focasoftware.com
  #baseUrl: /status
  logoUrl: https://i.ibb.co/hMrxNzb/Logo-Foca-1.png
  name: Foca Software
  introTitle: "**Uptime** is service health dashboarde and endpoints monitor"
  introMessage: This is a status page that uses **real-time** data from Foca Software services
  navbar:
    - title: Status
      href: /
    - title: Foca Software
      href: http://www.focasoftware.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
